// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPQq2PW9cdefmXE-2NrOE-rv4larQMUV0',
    appId: '1:1025649649569:web:b92019ba55b655d7e40de0',
    messagingSenderId: '1025649649569',
    projectId: 'internshipflutter1',
    authDomain: 'internshipflutter1.firebaseapp.com',
    storageBucket: 'internshipflutter1.firebasestorage.app',
    measurementId: 'G-7C1MV1814E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCem_p_V6xa1CB2AZJXTX5NqTIyKnEvDRE',
    appId: '1:1025649649569:android:b7d78cdb530624eae40de0',
    messagingSenderId: '1025649649569',
    projectId: 'internshipflutter1',
    storageBucket: 'internshipflutter1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARxM8TQU92AEzgJ36ogggREj3L6-alkpY',
    appId: '1:1025649649569:ios:dc55a090caae496de40de0',
    messagingSenderId: '1025649649569',
    projectId: 'internshipflutter1',
    storageBucket: 'internshipflutter1.firebasestorage.app',
    iosBundleId: 'com.example.internshipflutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARxM8TQU92AEzgJ36ogggREj3L6-alkpY',
    appId: '1:1025649649569:ios:dc55a090caae496de40de0',
    messagingSenderId: '1025649649569',
    projectId: 'internshipflutter1',
    storageBucket: 'internshipflutter1.firebasestorage.app',
    iosBundleId: 'com.example.internshipflutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPQq2PW9cdefmXE-2NrOE-rv4larQMUV0',
    appId: '1:1025649649569:web:fef9a8310c29a65ce40de0',
    messagingSenderId: '1025649649569',
    projectId: 'internshipflutter1',
    authDomain: 'internshipflutter1.firebaseapp.com',
    storageBucket: 'internshipflutter1.firebasestorage.app',
    measurementId: 'G-6N5HLMEFR0',
  );
}